name: Quality

on:
  push:
  pull_request:

jobs:
  php-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"

      - name: Lint Script
        run: php -l hello-world.php

      - name: Run Script
        run: php hello-world.php

